{{- if and .Values.openstack.username .Values.openstack.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "fugacloud-credentials" .Values.credentialsSecret }}
  labels:
    app: "{{ template "designate-certmanager-webhook.fullname" . }}"
    chart: "{{ template "designate-certmanager-webhook.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.openstack.username }}
  OS_USERNAME: {{ .Values.openstack.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.password }}
  OS_PASSWORD: {{ .Values.openstack.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.project_id }}
  OS_PROJECT_ID: {{ .Values.openstack.project_id | b64enc | quote }}
  {{- else if .Values.openstack.project_name }}
  OS_PROJECT_NAME: {{ .Values.openstack.project_name | b64enc | quote }}
  {{- else }}
  {{- fail "project_id or project_name is needed!" }}
  {{- end }}
  {{- if .Values.openstack.region_name }}
  OS_REGION_NAME: {{ .Values.openstack.region_name | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.auth_url }}
  OS_AUTH_URL: {{ .Values.openstack.auth_url | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.domain_name }}
  OS_DOMAIN_NAME: {{ .Values.openstack.domain_name | b64enc | quote }}
  {{- end }}
{{- end }}
